### ISSUE TITLE
Critical : Kamailio is not starting when enabling dispatcher Ubuntu 18.04

### ISSUE THREAD

**Issue by AmulTyagi** [kamailio/kamailio-docs#16]
Below given are the logs , when load the module from config files dispatcher.so , Kamailio is not starting . please find the below logs for your reference :

root@CICTPH01LLB01:/usr/lib/x86_64-linux-gnu/kamailio/modules# kamailio -E
 0(19009) INFO: <core> [core/sctp_core.c:74]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
Listening on
             udp: 127.0.0.1:5060
             udp: 192.168.180.200:5060
             tcp: 127.0.0.1:5060
             tcp: 192.168.180.200:5060
Aliases:
             tcp: CICTPH01LLB01:5060
             tcp: localhost:5060
             udp: CICTPH01LLB01:5060
             udp: localhost:5060

 0(19009) INFO: <core> [core/tcp_main.c:4735]: init_tcp(): using epoll_lt as the io watch method (auto detected)
 0(19011) INFO: rr [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
 0(19011) INFO: rr [rr_mod.c:177]: mod_init(): outbound module not available
 0(19011) INFO: auth [auth_mod.c:347]: mod_init(): qop set, but nonce-count (nonce_count) support disabled
 0(19011) INFO: <core> [main.c:2683]: main(): processes (at least): 32 - shm size: 67108864 - pkg size: 8388608
 0(19011) INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
 0(19011) INFO: <core> [core/udp_server.c:205]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
 0(19011) INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
 0(19011) INFO: <core> [core/udp_server.c:205]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
21(19044) INFO: jsonrpcs [jsonrpcs_sock.c:443]: jsonrpc_dgram_process(): a new child 0/19044
root@CICTPH01LLB01:/usr/lib/x86_64-linux-gnu/kamailio/modules# 22(19053) INFO: ctl [io_listener.c:214]: io_listen_loop(): io_listen_loop:  using epoll_lt io watch method (config)

=================================================================================================================

Feb 18 18:33:19 CICTPH01LLB01 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
Feb 18 18:33:19 CICTPH01LLB01 kamailio: INFO: <core> [core/sctp_core.c:74]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sct
p module
Feb 18 18:33:19 CICTPH01LLB01 kamailio: INFO: <core> [core/tcp_main.c:4735]: init_tcp(): using epoll_lt as the io watch method (auto detected)
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]: Listening on
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              udp: 127.0.0.1:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              udp: 192.168.180.200:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              tcp: 127.0.0.1:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              tcp: 192.168.180.200:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]: Aliases:
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              tcp: CICTPH01LLB01:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              tcp: localhost:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              udp: CICTPH01LLB01:5060
Feb 18 18:33:19 CICTPH01LLB01 kamailio[18815]:              udp: localhost:5060
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: rr [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: rr [rr_mod.c:177]: mod_init(): outbound module not available
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: auth [auth_mod.c:347]: mod_init(): qop set, but nonce-count (nonce_count) support disabled
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [main.c:2683]: main(): processes (at least): 32 - shm size: 67108864 - pkg size: 8388608
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [core/udp_server.c:205]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [core/udp_server.c:205]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: ERROR: <core> [core/tcp_main.c:2863]: tcp_init(): bind(d, 0x7f81495f1efc, 16) on 127.0.0.1:5060 : Address already in use
Feb 18 18:33:19 CICTPH01LLB01 /usr/sbin/kamailio[18817]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Feb 18 18:33:19 CICTPH01LLB01 systemd[1]: kamailio.service: Control process exited, code=exited status=255
Feb 18 18:33:19 CICTPH01LLB01 systemd[1]: kamailio.service: Failed with result 'exit-code'.
Feb 18 18:33:19 CICTPH01LLB01 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: kamailio.service: Service hold-off time over, scheduling restart.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 5.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: kamailio.service: Start request repeated too quickly.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: kamailio.service: Failed with result 'exit-code'.
Feb 18 18:33:20 CICTPH01LLB01 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.

Thanks
Amul Tyagi

**Comment by miconda** [comment]
This is issue tracker related to the content of the documents stored in this repository. Questions about configuring and using kamailio have to be directed to sr-users@lists.kamailio.org mainling list.
