### ISSUE TITLE
Logos in kamailio.org /pub/kamailio-logos/current are not

### ISSUE THREAD

**Issue by kkm000** [kamailio/kamailio-docs#19]
Not sure if this is the right repo to open this issue in, but can find no better contact.

While drawing an architecture diagram, I googled for "current Kamailio logo", and this link came up near the top:

https://www.kamailio.org/pub/kamailio-logos/current/Kamailio-Logo-Images/

The logos in this directory, and generally in /pub/kamailio-logos are dated 2015–2017, and are... just dated. The current logo is flat, not 3D-extruded with shadows (sooo 2010s!), and Wikipedia and the home page at kamailio.org agree on the flat one. It would be perfect to redirect these URLs (the whole `/pub/kamailio-logos/*`, likely—everything looks stale in the whole subtree) to the location of the current official logos, which I'm yet to find. Just deleting the directory would be not as helpful yet as a redirect, since search engines still rank it high, so people like me searching for the "current logo" could be sent to the right place faster.

Thank you!

**Comment by miconda** [comment]
The link you found is for the folder with some images having the logo over. If you go to the main page of kamailio.org, at the bottom is the navigation menu and in the group with `More Resources`, there is `Logos`, which points to:

  * https://www.kamailio.org/pub/kamailio-logos/current/

I think it offers pretty good visibility, and we cannot control how search engines index the web.

Otherwise, this is the tracker for kamailio-docs repo, should be used for reporting issues with the content in this repo.

**Comment by kkm000** [comment]
@miconda, oh, so these logos are current and official. The 3D logo, and two apparently identical sets of differently named files with the mtime 13 days apart for the flat logo. I really mistook the directory for an old or orphan one, which it's not. Apologies and thanks.

```
$ cmp kamailio-logo.ai kamailio-logo-2015.ai
$
```

> this is the tracker for kamailio-docs repo, should be used for reporting issues with the content in this repo.

That's a stern retort, man! I'm really sorry about my reporting it here. Do you perchance know of/could suggest a mailing list or any other way to ask a question about the logo/artwork usage?

**Comment by henningw** [comment]
If you want to ask about topics related to copyright or other commercial usage for the logos, you should contact our management list. Details at https://www.kamailio.org/w/management/
General usage questions can be asked at our sr-users list.
