### ISSUE TITLE
kamailio is not compiling and showing the below error

### ISSUE THREAD

**Issue by NagaBhushanaChari** [kamailio/kamailio-docs#24]
make[2]: Entering directory '/usr/local/src/kamailio/src/modules/stirshaken'
Makefile.defs defs skipped
gcc -fPIC -DPIC -g -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -pthread -DKSR_PTHREAD_MUTEX_SHARED -Wall    -DNAME='"kamailio"' -DVERSION='"5.5.5"' -DARCH='"x86_64"' -DOS='linux_' -DOS_QUOTED='"linux"' -DCOMPILER='"gcc 7.5.0"' -D__CPU_x86_64 -D__OS_linux -DVERSIONVAL=5005005 -DCFG_DIR='"/usr/local/etc/kamailio/"' -DSHARE_DIR='"/usr/local/share/kamailio/"' -DRUN_DIR='"/var/run/kamailio/"' -DPKG_MALLOC -DSHM_MMAP -DDNS_IP_HACK -DUSE_MCAST -DUSE_TCP -DDISABLE_NAGLE -DHAVE_RESOLV_RES -DUSE_DNS_CACHE -DUSE_DNS_FAILOVER -DUSE_DST_BLOCKLIST -DUSE_NAPTR -DWITH_XAVP -DMEM_JOIN_FREE -DF_MALLOC -DQ_MALLOC -DTLSF_MALLOC -DDBG_SR_MEMORY -DUSE_TLS -DTLS_HOOKS -DUSE_CORE_STATS -DSTATISTICS -DMALLOC_STATS -DUSE_SCTP -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DCC_GCC_LIKE_ASM -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_SCHED_SETSCHEDULER -DHAVE_IP_MREQN -DUSE_RAW_SOCKS -DHAVE_EPOLL -DHAVE_SIGIO_RT -DSIGINFO64_WORKARROUND -DUSE_FUTEX -DHAVE_SELECT  -I. -DMOD_NAME='"stirshaken"' -c stirshaken_mod.c -o stirshaken_mod.o -MMD -MP
stirshaken_mod.c:28:10: fatal error: stir_shaken.h: No such file or directory
 #include <stir_shaken.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [stirshaken_mod.o] Error 1
../../Makefile.rules:100: recipe for target 'stirshaken_mod.o' failed
make[2]: Leaving directory '/usr/local/src/kamailio/src/modules/stirshaken'
make[1]: *** [modules] Error 1
Makefile:511: recipe for target 'modules' failed
make[1]: Leaving directory '/usr/local/src/kamailio/src'
make: *** [all] Error 2
Makefile:34: recipe for target 'all' failed

**Comment by NagaBhushanaChari** [comment]
@linuxmaniac hello sir I am seeking the solution for that issue, can u please help me to solve this issue

**Comment by linuxmaniac** [comment]
The bug tracker is for bugs, not for general discussion. Please ask this question on the mailing lists. Thanks.
https://www.kamailio.org/w/mailing-lists/
