### ISSUE TITLE
modules.lst missing

### ISSUE THREAD

**Issue by goharahmed** [kamailio/kamailio-docs#3]
REf to Wiki page: 

[Kamailio 5.0 Installation from Git](http://kamailio.org/docs/tutorials/5.0.x/kamailio-install-guide-git/#prerequisites)

Under the heading "**Tuning Makefiles**" after the step '_make cfg_' the modules.lst file doesn't exist at the same directory instead its located inside src/ folder.

I wonder if this is me missing a step or the 'make cfg' not linking the file in main kamailio directory.

I do:
```
vim src/modules.lst
```

Later on, the kamailio.default path is wrong as well:

The path should be:

```
/usr/local/src/kamailio-5.0/kamailio/pkg/kamailio/deb/debian/kamailio.default
```

**Comment by miconda** [comment]
Thanks, should be fixed in git and they will be uploaded soon to the website.
