### ISSUE TITLE
macos - make install error

### ISSUE THREAD

**Issue by ankoosmca** [kamailio/kamailio-docs#4]
![screen shot 2017-03-29 at 7 57 37 am](https://cloud.githubusercontent.com/assets/15854130/24435910/b52dfb2e-1455-11e7-8ca5-6a40052f7a2c.png)

```
install -m 755  usrloc.so  /usr/local/lib64/kamailio/modules
touch           /usr/local/lib64/kamailio/modules/xhttp.so
install -m 755  xhttp.so  /usr/local/lib64/kamailio/modules
touch           /usr/local/lib64/kamailio/modules/xhttp_rpc.so
install -m 755  xhttp_rpc.so  /usr/local/lib64/kamailio/modules
touch           /usr/local/lib64/kamailio/modules/xlog.so
install -m 755  xlog.so  /usr/local/lib64/kamailio/modules
touch           /usr/local/lib64/kamailio/modules/xprint.so
install -m 755  xprint.so  /usr/local/lib64/kamailio/modules
/bin/sh: i: command not found
make[1]: *** [install-cfg] Error 127
make: *** [install] Error 2
Macs-MBP:kamailio mac$ 
```

**Comment by miconda** [comment]
I noticed this sometime on mac, being unable to find quickly a solution, expecting it is a issue related to the sed implementation there. Run it once again and it should just work.

Anyhow, this bug tracker is for reporting errors in the documentation files, not a forum for kamailio tutorials or usage. For such questions, send an email to sr-users@lists.sip-router.org
