### ISSUE TITLE
getting connection error on softphone when I install kamailio on google cloud instance

### ISSUE THREAD

**Issue by shrutiathawale** [kamailio/kamailio-docs#5]

**Comment by miconda** [comment]
Not related.

**Comment by shrutiathawale** [comment]
i installed kamailio sip server on google cloud instance. when i run 'sudo
service kamailio start' it shows sip server is running. but when i try to
register on softphone, it gives connection error. I made changes according
to NAT settings. what is missing then ? i m using public ip of google
instance to register

Thanks & Regards,
Shruti Athawale

**Comment by miconda** [comment]
This is the bug tracker for kamailio-docs repo, you seem to try to sort out issues with a use case of kamailio, for that use the sr-users@lists.kamailio.org mailing list:

  * https://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-users
